export const LOG_IN_ACTION = 'LOG_IN';
export const LOG_OUT_ACTION = 'LOG_OUT';

export const NEW_RESERVED_CONTEXTS = 'RESERVED_CONTEXTS';
export const SELECTED_RESERVED_CONTEXT = 'SELECTED_RESERVED_CONTEXT';

